# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09e444643b5bf12e5ff4969f22f9ca9b5db74d42d4e1f7780324ae3575545fee5633104ba6b33ec52fe4eab30ff74be661f1d25bab020f2d65c8ea2f4f1e77b2

test:
  secret_key_base: 11dff7503496e2379403884edddcaff5920246942df8b5178b3c56214c61f7ed4be72ef46df54b20981a4d2416587f09a991c7e65bac83aabb1c34ed8b7c61ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
